---

# Tasks file to "configure_date_and_time"

 - name: "configure_date_and_time: Copy from ntp.conf.j2 to {{ETC_NTP_FILE}}"
   template:
     src=templates/ntp.conf.j2
     dest={{ETC_NTP_FILE}}
     owner=root
     group=root
     mode=0644
     backup=yes

 - name: "configure_date_and_time: Remove old backups"
   shell: |
     find /etc -maxdepth 1 -name "ntp.conf.*@*~" -type f -print0 | xargs -0r ls -1t | tail -n+2 | xargs -rd '\n' rm
     find /etc -maxdepth 1 -name "ntp.conf.bck*" -type f -print0 | xargs rm
   ignore_errors: true

 - name: "configure_date_and_time: Ajust timezone to America/Sao_Paulo"
   shell:
     timedatectl set-timezone America/Sao_Paulo
   register: ajust_timezone

 - name: "configure_date_and_time: Ensures ntp service is restarted"
   service:
     name=ntp
     state=restarted
