sonar.host.url=https://sonar.local

sonar.projectKey=<sonarkey>
sonar.projectName=<customer> - <project>
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.exclusions=**/build/**,**/node_modules/**,**/public/libs/**,**/target/**,**/.tmp/**

sonar.java.binaries=target/classes
# sonar.java.libraries=target/lib/*.jar
sonar.tests=src/test/java

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.pitest.mode=reuseReport
sonar.pitest.reportsDirectory=target/reports
sonar.coverage.exclusions=**/<file>.java
sonar.dynamicAnalysis=reuseReports
#sonar.language=<language>
