pool:
  name: 'pool-linux'

trigger:
  branches:
    include:
    - '*'
  tags:
    include: 
    - '*'
  paths:
    exclude:
    - 'README.md'

schedules:
- cron: "0 1 * * *"
  displayName: 'Nightly Build'
  branches:
    include:
    - development

variables:
  BranchDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/development')]
  BranchQA: $[eq(variables['Build.SourceBranch'], 'refs/heads/qa')]
  BranchProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  TagDev: $[contains(variables['Build.SourceBranch'], 'refs/tags/dev-')]
  TagQA: $[contains(variables['Build.SourceBranch'], 'refs/tags/qa-')]
  TagProd: $[contains(variables['Build.SourceBranch'], 'refs/tags/prod-')]  

jobs:

- job: ci
  displayName: 'CI (Continuous Integration)'
  condition: succeeded()
  variables:
    DotNETCoreVersion: '3.1.406'  
    NodeVersion: '14.x'
    ShiftLeftReportPath: '/reports/ShiftLeftScanner'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    displayName: 'Checkout SCM'
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NodeVersion)'
    displayName: 'Install Node.JS tool'
  - script:
      npm install
      npm run build
    displayName: 'Install modules and run build command'
  - script:
      npm run test
    displayName: 'Run Unit Tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Unit Tests Results'
    displayName: 'Publish Unit Tests Results'
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '$(DotNETCoreVersion)'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .NET Core SDK'  
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: 'coverage/cobertura-coverage.xml'
      failIfCoverageEmpty: false
    displayName: 'Publish Code Coverage Result'
  - script: sonar-scanner
    displayName: 'Run SonarQube Analisys'
  - script: sonar-quality-gate
    displayName: 'Run SonarQube Quality Gate'
  - script: |
      docker run \
        -e 'VDB_HOME=/tmp' \
        -v '$(Build.SourcesDirectory):/app' \
        -v '$(Build.ArtifactStagingDirectory):/reports' \
        -u $(id -u):$(id -g) \
        shiftleft/sast-scan scan --src /app --build \
        --out_dir /reports/CodeAnalysisLogs || true
    displayName: 'Perform ShiftLeft Security Scanner'
    continueOnError: 'true'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish ShiftLeft Report'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'

- job: cd
  displayName: 'CD (Continuous Delivery)'
  dependsOn: 'ci'
  condition: and(succeeded(), or(eq(variables.TagDev, true), eq(variables.TagQA, true), eq(variables.TagProd, true)))
  variables:
    DockerfilePath: './Dockerfile' 
    DockerImageName: 'devops.azurecr.io/calculator'
    DockerImageVersion: '$(Build.SourceBranchName)'
    DOCKER_BUILDKIT: 1
  steps:
  - task: Docker@2
    displayName: 'Build and Push image to ACR'
    inputs:
      command: buildAndPush
      repository: '$(DockerImageName)'
      dockerfile: '$(DockerfilePath)'
      containerRegistry: 'ACR'
      tags: |
        '$(DockerImageVersion)'
