sonar.host.url=https://devops-sandbox.venturus.org.br

sonar.projectKey=CALC
sonar.projectName=DevOps - Calculator
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/build/**,**/node_modules/**,**/public/libs/**,**/target/**,**/.tmp/**
#sonar.java.binaries=src/target/classes
#sonar.java.libraries=target/lib/*.jar
#sonar.tests=src/test/java

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

#sonar.testExecutionReportPaths=out/test-results.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=node+modules/*,coverage/*,test/*

sonar.dynamicAnalysis=reuseReports
#sonar.language=<language>
