#!/usr/bin/env groovy

/**
 * Importing common Venturus Libs
 * All shared libraries are available in the repository:
 * https://gitlab.local/shared/ci-utils/jenkins
 */
@Library('SharedLibs')_

/**
 * Build and Project settings
 */
env.BuildPath = "."

/**
 * Git settings
 */
env.GitURL = "https://gitlab.local/<project_customer>/<project_group>/<project_name>"
env.GitCredentials = "<git_credentials>"

/**
 * Jira settings
 */
env.JiraKey = "<jira_key>"
env.JiraJQL = "PROJECT = '${JiraKey}' and (status = Finished and (issuetype = Bug OR issuetype = Improvement OR issuetype = Story) or (issuetype = Story and status = Done)) and Sprint in openSprints() and created > startOfYear() and 'Integrated Version' is EMPTY ORDER BY Rank ASC"
env.JiraTransitionId = "201"

/**
 * Notification settings
 */
env.EmailRecipients = "<notification_email_recipients>"
env.TeamsWebHook = "<notification_teams_webhook>"

/**
 * Rancher and Docker settings
 * For tips to configure variables below, see:
 * - https://devops.local/site/pages/rancher
 * - https://devops.local/site/pages/docker
 */
env.RancherUser = "<rancher_user>"
env.RancherToken = "<rancher_token>"
env.RancherServer = "https://rancher.local/k8s/clusters/c-5fgmv"
env.RancherCluster = "venturus"
env.RancherSecret = "<project_customer>-hosted"

/**
 * Tools variables configurations
 */
env.AntVersion = "1.10.5"
env.DotNETVersion = "3.1"
env.GradleVersion = "4.9"
env.JdkVersion = "8"
env.MavenVersion = "3.5.4"
env.MSBuildVersion = "16.0.461.62831"
env.NodeVersion = "lts"

/**
 * Sonar settings
 */
env.SonarVersion = "7.9.3"
env.SonarRunnerVersion = "4.3.0"
env.SonarURL = "https://sonar.local"
env.SonarProjectKey = "<sonar_project_key>"
env.SonarMinPercentage = "30"
env.SonarExclusions = "**/*.tmp"

/**
 * Main pipeline definition
 */
pipeline {
    agent { label 'pipeline' }
    /** Available agents:
     * Mac OS  = mac
     * Ubuntu  = pipeline
     * Windows = win10
     */

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5', artifactDaysToKeepStr: ''))
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS')
    }

    environment {
        //ENV_VARS_DEBUG = EnvVarsDebug()
        ENV_VARS_DEFAULT = EnvVarsDefault()
    }

    //tools {
        //ant "ant-${AntVersion}"
        //gradle "gradle-${GradleVersion}"
        //jdk "jdk${JdkVersion}"
        //maven "maven-${MavenVersion}"
        //msbuild "msbuild-${MSBuildVersion}"
    //}

    stages {

        stage('Prepare') {
            steps {
                echo "Clonning repository... [${env.GitURL}]"
                GitClone()
            }
        }

        stage('Build') {
            steps {
                dir(BuildPath) {
                    echo "Performing installation and build process..."
                    sh "pip3 install --upgrade pip"
                    sh "pip3 install -r requirements.txt"
                }
            }
        }

        stage('Unitary Tests') {
            steps {
                dir(BuildPath) {
                    echo "Running Unit Tests"
                    sh "pytest --cov-report xml --cov=. --cov-fail-under=0 test/unit -v"
                }
            }
        }

        stage('Static Analysis') {
            steps {
                dir(BuildPath) {
                    echo "Running lint tools"
                    sh "pylint tasks/*.py"
                }
                script {
                    if (fileExists ('sonar-project.properties')) {
                        echo "Running static analysis tool"
                        SonarQube()
                        //SonarQubeQualityGate()
                    }
                }
            }
        }

        stage('Deploy to Dev') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('development')
                }
            }
            steps {
                dir(BuildPath) {
                    // Deploy to Development Commands...
                    script {
                        TagName = "${env.gitlabSourceBranch}"
                        TagName = TagName.replaceAll "refs/tags/", ""
                        currentBuild.displayName = "${TagName}"
                        currentBuild.setKeepLog(true)
                        //JiraIntegratedVersion()
                        //EmailNotificationRelease()
                        //TeamsNotificationRelease()                        
                    }
                }
            }
        }

        stage('Deploy to QA') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('refs/tags/qa-')
                }
            }
            steps {
                dir(BuildPath) {
                    // Deploy to QA Commands...
                    script {
                        TagName = "${env.gitlabSourceBranch}"
                        TagName = TagName.replaceAll "refs/tags/", ""
                        currentBuild.displayName = "${TagName}"
                        currentBuild.setKeepLog(true)
                        //JiraIntegratedVersion()
                        //EmailNotificationRelease()
                        //TeamsNotificationRelease()                        
                    }
                }
            }
        }

        stage('Deploy to Prod') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('refs/tags/prod-')
                }
            }
            steps {
                dir(BuildPath) {
                    // Delivery to Production Commands...
                    script {
                        TagName = "${env.gitlabSourceBranch}"
                        TagName = TagName.replaceAll "refs/tags/", ""
                        currentBuild.displayName = "${TagName}"
                        currentBuild.setKeepLog(true)
                        //JiraIntegratedVersion()
                        //EmailNotificationRelease()
                        //TeamsNotificationRelease()                        
                    }
                }
            }
        }

    }

    post {
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
            updateGitlabCommitStatus name: 'build', state: 'failed'
            //EmailNotification()
            //TeamsNotification()
        }
        success {
            script {
                currentBuild.result = 'SUCCESS'
            }
            updateGitlabCommitStatus name: 'build', state: 'success'
            //EmailNotification()
            //TeamsNotification()
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    currentBuild.result = 'SUCCESS'
                    //EmailNotification()
                    //TeamsNotification()
                }
            }
        }
        always {
            cleanWs()
        }
    }
}
