sonar.host.url=https://sonar.local

sonar.projectKey=<sonar_project_key>
sonar.projectName=<project_customer> - <project_name>
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/build/**,**/node_modules/**,**/public/libs/**,**/target/**,**/.tmp/**

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

sonar.python.pylint=/usr/local/bin/pylint
sonar.python.pylint_config=.pylintrc
sonar.python.pylint.reportPath=pylint-report.txt	
sonar.python.xunit.reportPath=test-reports/*.xml
sonar.python.coverage.reportPath=coverage.xml

sonar.dynamicAnalysis=reuseReports
#sonar.language=<language>
