rocommunity	zabbix		0.0.0.0/0

view		all-mibs	included	.1	80
view		systemview	included	.1.3.6.1.2.1.1
view		systemview	included	.1.3.6.1.2.1.25.1.1

includeAllDisks 20%

proc apache2		1 5
proc docker		1 1
proc java		1 1
proc mysqld		1 1
proc nginx		1 1
proc ntpd		1 1
proc postgres		1 5
proc rpcbind		1 1
proc snmpd		1 1
proc sshd		1 3

extend {{ HOST_NAME }}_root_partition_percent_used "/usr/local/bin/{{ HOST_NAME }}_ram_memory_percent_used.sh"
extend {{ HOST_NAME }}_root_partition_percent_used "/usr/local/bin/{{ HOST_NAME }}_root_partition_percent_used.sh"
extend {{ HOST_NAME }}_uptime "/usr/local/bin/{{ HOST_NAME }}_uptime.sh"
