---

# Defaults file for "server_monitoring" role

ETC_SNMP_FILE: "/etc/snmp/snmpd.conf"
ETC_SNMP_PATH: "/etc/snmp"
RSYSLOG_DEST: "/etc/rsyslog.d/50-default.conf"
USR_LOCAL_BIN_PATH: "/usr/local/bin"
