---

# Main tasks file for "server_configuration" role

- import_tasks: "configure_date_and_time.yml"
  tags: ["configure_date_and_time"]

- import_tasks: "configure_locale.yml"
  tags: ["configure_locale"]

- import_tasks: "configure_variables_and_path.yml"
  tags: ["configure_variables_and_path"]

- import_tasks: "update_hosts_file.yml"
  tags: ["update_hosts_file"]

- import_tasks: "configure_resolvconf.yml"
  tags: ["configure_resolvconf"]
