# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :build_ipa do |options|

  version = get_version_number(xcodeproj: "<project>.xcodeproj")
  b_number = get_build_number(xcodeproj: "<project>.xcodeproj", hide_error_when_versioning_disabled: true)

  output_dir = (options[:output_dir] ? options[:output_dir] : "ipa")
  scheme = (options[:scheme] ? options[:scheme] : "iosApp")
  configuration = (options[:configuration] ? options[:configuration] : "Release")
  output_name = "iosApp-" + configuration + "-v" + version + "-" + Time.new.strftime("%Y-%m-%dT%H-%M") + ".ipa"

  build_app(scheme: scheme,
  configuration: configuration,
  silent: false,
  clean: true,
  output_directory: output_dir, # Destination directory. Defaults to current directory.
  output_name: output_name,       # specify the name of the .ipa file to generate (including file extension)
  export_options: {
      method: "enterprise",
      provisioningProfiles:{
        "PRODUCT_BUNDLE_IDENTIFIER": "{PROVISIONING_PROFILE_SPECIFIER}"
      },
      signingStyle: "manual"
    }
  )
end
