sonar.host.url=https://sonar.local

sonar.projectKey=<sonarkey>
sonar.projectName=<customer> - <project>
sonar.projectVersion=1.0

sonar.sources=<project>
sonar.tests=<project>.Tests

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

sonar.swift.project=<project>.xcodeproj
sonar.swift.workspace=<project>.xcworkspace
sonar.swift.appScheme=<project>
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=10.0
# sonar.swift.appConfiguration=Release
sonar.swift.excludedPathsFromCoverage=.*Tests.*
sonar.swift.tailor.config=--max-line-length=100 --max-file-length=500 --max-name-length=40 --min-name-length=4

sonar.junit.reportsPath=reports/
sonar.junit.include=*.junit
sonar.swift.lizard.report=reports/lizard-report.xml
sonar.swift.coverage.reportPattern=reports/cobertura.xml
sonar.swift.swiftlint.report=reports/*swiftlint.txt

sonar.dynamicAnalysis=reuseReports
sonar.language=swift
