#!/usr/bin/env groovy

/**
 * Importing common Venturus Libs
 * All shared libraries are available in the repository:
 * https://gitlab.local/shared/ci-utils/jenkins
 */
@Library('SharedLibs')_

/**
 * Build and Project settings
 */
env.BuildPath = "."

/**
 * Git settings
 */
env.GitURL = "https://gitlab.local/<project_customer>/<project_group>/<project_name>"
env.GitCredentials = "<git_credentials>"

/**
 * Jira settings
 */
env.JiraKey = "<jira_key>"
env.JiraJQL = "PROJECT = '${JiraKey}' and (status = Finished and (issuetype = Bug OR issuetype = Improvement OR issuetype = Story) or (issuetype = Story and status = Done)) and Sprint in openSprints() and created > startOfYear() and 'Integrated Version' is EMPTY ORDER BY Rank ASC"
env.JiraTransitionId = "201"

/**
 * Notification settings
 */
env.EmailRecipients = "<notification_email_recipients>"
env.TeamsWebHook = "<notification_teams_webhook>"

/**
 * Rancher and Docker settings
 * For tips to configure variables below, see:
 * - https://devops.local/site/pages/rancher
 * - https://devops.local/site/pages/docker
 */
env.RancherUser = "<rancher_user>"
env.RancherToken = "<rancher_token>"
env.RancherServer = "https://rancher.local/k8s/clusters/c-5fgmv"
env.RancherCluster = "venturus"
env.RancherSecret = "<project_customer>-hosted"

/**
 * Tools variables configurations
 */
env.AntVersion = "1.10.5"
env.DotNETVersion = "3.1"
env.GradleVersion = "4.9"
env.JdkVersion = "8"
env.MavenVersion = "3.5.4"
env.MSBuildVersion = "16.0.461.62831"
env.NodeVersion = "lts"

/**
 * Sonar settings
 */
env.SonarVersion = "7.9.3"
env.SonarRunnerVersion = "4.3.0"
env.SonarURL = "https://sonar.local"
env.SonarProjectKey = "<sonar_project_key>"
env.SonarMinPercentage = "30"
env.SonarExclusions = "**/*.tmp"

/**
 * Main pipeline definition
 */
pipeline {
    agent { label 'pipeline' }
    /** Available agents:
     * Mac OS  = mac
     * Ubuntu  = pipeline
     * Windows = win10
     */

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5', artifactDaysToKeepStr: ''))
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS')
    }

    environment {
        //ENV_VARS_DEBUG = EnvVarsDebug()
        ENV_VARS_DEFAULT = EnvVarsDefault()
    }

    //tools {
        //ant "ant-${AntVersion}"
        //gradle "gradle-${GradleVersion}"
        //jdk "jdk${JdkVersion}"
        //maven "maven-${MavenVersion}"
        //msbuild "msbuild-${MSBuildVersion}"
    //}

    stages {

        stage('Prepare') {
            steps {
                echo "Clonning repository... [${env.GitURL}]"
                GitClone()
            }
        }

        stage('Build') {
            steps {
                dir(BuildPath) {
                    echo "Performing installation and build process..."
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }

        stage('Unitary Tests') {
            steps {
                dir(BuildPath) {
                    echo "Running Unit Tests"
                    sh "npm run test:headless"
                }
            }
        }

        stage('Static Analysis') {
            steps {
                dir(BuildPath) {
                    echo "Running lint tools"
                    sh "npm run lint"
                }
                script {
                    if (fileExists ('sonar-project.properties')) {
                        echo "Running static analysis tool"
                        SonarQube()
                        //SonarQubeQualityGate()
                    }
                }
            }
        }

       stage('Deploy to Dev') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('development')
                }
            }
            steps {
                script {
                    env.RancherDockerRegistryImageVersion = "latest"
                    env.RancherDockerRegistryImage = "docker.local:<port>/<project>/<deployment>/development/<deployment>"
                    env.RancherNamespace = "<customer>-<project>-development"
                    env.RancherComposeFile = "docker-compose-dev.yaml"                        
                    dir(BuildPath) {
                        sh "docker build -t ${RancherDockerRegistryImage}:${RancherDockerRegistryImageVersion} ."
                        sh "docker push ${RancherDockerRegistryImage}:${RancherDockerRegistryImageVersion}"
                    }
                    sh "sed -i 's|IMAGE_VERSION|${RancherDockerRegistryImageVersion}|g' ${RancherComposeFile}"
                    RancherDeployCompose()
                }
                script {
                    env.RancherDeployment = "<deployment>"
                    env.RancherNodePort = "<port>"
                    RancherChangeNodePort("${env.RancherDeployment}", "${env.RancherNameSpace}", "${RancherNodePort}")
                }
                script {
                    TagName = "${env.gitlabSourceBranch}"
                    TagName = TagName.replaceAll "refs/tags/", ""
                    //currentBuild.displayName = "${TagName}"
                    //currentBuild.setKeepLog(true)
                    //JiraIntegratedVersion()
                    EmailNotificationRelease()
                    //TeamsNotificationRelease()                        
                }
            }
        }

        stage('Deploy to QA') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('refs/tags/qa-')
                }
            }
            steps {
                dir(BuildPath) {
                    script {
                        ImageVersion = "${env.gitlabSourceBranch}"
                        env.VenturusDockerRegistryImage = "docker.local:<port>/<project>/<deployment>/qa/<deployment>"
                        env.AWSDockerRegistryImage = "<account>.dkr.ecr.us-east-1.amazonaws.com/<customer>/<project>/qa/<deployment>"
                        env.AWSDockerRegistryImageVersion = ImageVersion.replaceAll "refs/tags/", ""
                        env.AWSClusterName = "<eks-cluster-name>"
                        env.AWSRegion = "us-east-1"
                        env.AWSNamespace = "<project>-qa"
                        env.AWSComposeFile = "docker-compose-homolog.yml"
                        sh "docker build -f Dockerfile -t ${VenturusDockerRegistryImage}:${AWSDockerRegistryImageVersion} -t ${AWSDockerRegistryImage}:${AWSDockerRegistryImageVersion} ."
                        sh "docker push ${VenturusDockerRegistryImage}:${AWSDockerRegistryImageVersion}"
                        sh "sed -i 's|IMAGE_VERSION|${AWSDockerRegistryImageVersion}|g' ${AWSComposeFile}"
                    }
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: '<configname>']]) {
                        sh "aws ecr get-login-password --region ${AWSRegion} | docker login --username AWS --password-stdin ${AWSDockerRegistryImage}"
                        sh "docker push ${AWSDockerRegistryImage}:${AWSDockerRegistryImageVersion}"
                        sh "aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}"
                        sh "aws configure set aws_secret_access_key  ${AWS_SECRET_ACCESS_KEY}"
                        sh "aws configure set default.region us-east-1"
                        sh "aws configure set default.output json"
                        sh "aws eks --region ${AWSRegion} update-kubeconfig --name ${AWSClusterName}"
                        sh "kompose convert --file ${AWSComposeFile}"
                        sh "kubectl apply -f <deployment>.yaml --namespace=${AWSNamespace}"
                    }
                }
                script {
                    TagName = "${env.gitlabSourceBranch}"
                    TagName = TagName.replaceAll "refs/tags/", ""
                    currentBuild.displayName = "${TagName}"
                    currentBuild.setKeepLog(true)
                    //JiraIntegratedVersion()
                    EmailNotificationRelease()
                    //TeamsNotificationRelease()
                }    
            }
        }

        stage('Deploy to Prod') {
            when {
                expression {
                    return "${env.gitlabSourceBranch}".startsWith('refs/tags/prod-')
                }
            }
            steps {
                dir(BuildPath) {
                    script {
                        ImageVersion = "${env.gitlabSourceBranch}"
                        env.VenturusDockerRegistryImage = "docker.local:<port>/<project>/<deployment>/prod/<deployment>"
                        env.AzureDockerRegistryImage = "<account>.azurecr.io/<customer>/<project>/prod/<deployment>"
                        env.AzureDockerRegistryImageVersion = ImageVersion.replaceAll "refs/tags/", ""
                        sh "docker build -t ${VenturusDockerRegistryImage}:${AzureDockerRegistryImageVersion} -t ${AzureDockerRegistryImage}:${AzureDockerRegistryImageVersion} ."
                        sh "docker push ${VenturusDockerRegistryImage}:${AzureDockerRegistryImageVersion}"
                        env.AzureNamespace = "<project>-prod"
                        env.AzureComposeFile = "docker-compose-prod.yml"
                        sh "sed -i 's|BACKEND_IMAGE_VERSION|${AzureDockerRegistryImageVersion}|g' ${AzureComposeFile}"
                    }
                    withCredentials([azureServicePrincipal('<configname>')]) {
                        sh "az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID"
                        sh "az acr login --name <serviceprincipal>"
                        sh "docker push ${AzureDockerRegistryImage}:${AzureDockerRegistryImageVersion}"
                        sh "az aks get-credentials --resource-group ccr-qa-rg --name ccr-qa-aks"
                        sh "kubectl patch serviceaccount default -p '{\"imagePullSecrets\": [{\"name\": \"ccr-qa-aks\"}]}' || true"
                        sh "kompose convert --file ${AzureComposeFile}"
                        sh "kubectl apply -f <deployment>.yaml --namespace=${AzureNamespace}"
                    }
                    script {
                        TagName = "${env.gitlabSourceBranch}"
                        TagName = TagName.replaceAll "refs/tags/", ""
                        currentBuild.displayName = "${TagName}"
                        currentBuild.setKeepLog(true)
                    }
                    script {
                        //JiraIntegratedVersion()
                        EmailNotificationRelease()
                        TeamsNotificationRelease()
                    }    
                }
            }
        }

    }

    post {
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
            updateGitlabCommitStatus name: 'build', state: 'failed'
            EmailNotification()
            //TeamsNotification()
        }
        success {
            script {
                currentBuild.result = 'SUCCESS'
            }
            updateGitlabCommitStatus name: 'build', state: 'success'
            //EmailNotification()
            //TeamsNotification()
        }
        changed {
            script {
                if (currentBuild.currentResult == 'SUCCESS') {
                    currentBuild.result = 'SUCCESS'
                    EmailNotification()
                    //TeamsNotification()
                }
            }
        }
        always {
            cleanWs()
        }
    }
}
