sonar.host.url=https://sonar.local

sonar.projectKey=<sonar_project_key>
sonar.projectName=<project_customer> - <project_name>
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/build/**,**/node_modules/**,**/public/libs/**,**/target/**,**/.tmp/**

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.dynamicAnalysis=reuseReports
#sonar.language=<language>
