sonar.host.url=https://sonar.local

sonar.projectKey=<sonar_project_key>
sonar.projectName=<project_customer> - <project_name>
sonar.projectVersion=1.0

sonar.sources=app/src/main/java
sonar.exclusions=**/build/**,**/node_modules/**,**/public/libs/**,**/target/**,**/.tmp/**
#sonar.java.binaries=app/build/intermediates/classes
sonar.tests=app/src/test/java

sonar.log.level=INFO
sonar.verbose=false
sonar.sourceEncoding=UTF-8

sonar.android.lint.report=app/build/outputs/lint-results.xml
#sonar.junit.reportPaths=app/build/test-results/testUnitTest
#sonar.jacoco.reportPaths=app/build/jacoco/testUnitTest.exec

sonar.dynamicAnalysis=reuseReports
#sonar.language=<language>
